# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Portfolio
email: aelopez1996@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Alonzo Lopez's digital portfolio.
twitter_username: N/A
github_username: N/A
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# theme: minimal-mistakes-jekyll

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alonzo Lopez"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Professional roboticist, casual musician, avid learner."
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://alonzolopez.github.io/portfolio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alonzolopez"

footer:
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://alonzolopez.github.io/portfolio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alonzolopez"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # music
  - scope:
      path: ""
      type: music
    values:
      layout: single
      author_profile: true
      share: true
  # quotes
  # - scope:
  #     path: ""
  #     type: quotes
  #   values:
  #     layout: single
  #     author_profile: true
  #     share: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio: 
    output: true
    permalink: /:collection/:path/
  music:
    output: true 
    permalink: /:collection/:path/
  # quotes:
  #   output: true 
  #   permalink: /:collection/:path/